apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-banking-application
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    path: '\demo-open-banking\open-banking-chart'
    repoURL: 'git:\C:\xspace\lab\infra'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
