apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-banking
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    path: 'k8s-open-banking'
    repoURL: 'https://github.com/carlosdiandy/devops.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
