apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-banking
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: 'https://github.com/carlosdiandy/devops.git'
      path: k8s-open-banking
      targetRevision: HEAD
    - repoURL: 'https://github.com/carlosdiandy/devops.git'
      path: 'k8s-open-banking/open-banking-chart'
      targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
