apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
type: servicebinding.io/postgresql
stringData:
  type: "postgresql"
  provider: "postgresql"
  host: "demo-db"
  port: "5432"
  database: "petclinic"
  username: "postgres"
  password: "passer@123"