apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.app.name }}-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  endpoints:
    - path: /actuator/prometheus
      interval: 3s
      port: web-http
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
